#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build $@
echo "\nStart building libass"
scripts/libass-config 
scripts/libass-build $@
echo "libass building completed"
echo "\n\nStart building ffmpeg"
scripts/ffmpeg-config 
scripts/ffmpeg-build $@
echo "ffmpeg building completed"
echo "\n\nStart building mpv"
scripts/mpv-config 
scripts/mpv-build $@
echo "mpv build completed"

export SYSTEM = `uname -s`
if [ $SYSTEM = "Darwin" ] ; then
    echo "building mpv.app bundle..."
    TOOLS/osxbundle.py build/mpv
    TOOLS/dylib-unhell.py build/libmpv
    echo "mpv.app bundle is built."
fi
